# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ProtocGenGapiLint < Formula
  desc "A gapi-linter plugin for protoc"
  homepage "https://github.com/protoc-extensions/protoc-gen-gapi-lint"
  version "0.0.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/protoc-extensions/protoc-gen-gapi-lint/releases/download/v0.0.2/protoc-gen-gapi-lint_0.0.2_darwin_arm64.tar.gz"
      sha256 "1861ac2ba744b8c2d3b1bf8b8629e04a480872ee7896d5075aa49bba7f432c42"

      def install
        bin.install "protoc-gen-gapi-lint"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/protoc-extensions/protoc-gen-gapi-lint/releases/download/v0.0.2/protoc-gen-gapi-lint_0.0.2_darwin_amd64.tar.gz"
      sha256 "bb12987e27c438317409dd88accd39e24eeb2933f8e4c4748573e4ab49e5e5f4"

      def install
        bin.install "protoc-gen-gapi-lint"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/protoc-extensions/protoc-gen-gapi-lint/releases/download/v0.0.2/protoc-gen-gapi-lint_0.0.2_linux_arm64.tar.gz"
      sha256 "17eb00f7b5f801fd107056a5f9055f12c32e63ef4e2218aafed71c117be1a5bd"

      def install
        bin.install "protoc-gen-gapi-lint"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/protoc-extensions/protoc-gen-gapi-lint/releases/download/v0.0.2/protoc-gen-gapi-lint_0.0.2_linux_amd64.tar.gz"
      sha256 "76843e9b7a0b972b215b070903689718b828ea564945c24f3675d30ddf0d7290"

      def install
        bin.install "protoc-gen-gapi-lint"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/protoc-extensions/protoc-gen-gapi-lint/releases/download/v0.0.2/protoc-gen-gapi-lint_0.0.2_linux_armv6.tar.gz"
      sha256 "ecb668d9dd8441cbb3e5f75984b39c49f48469bb0e18a48b6588b7a49ba883a3"

      def install
        bin.install "protoc-gen-gapi-lint"
      end
    end
  end
end
