# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ProtocGenGoDefaults < Formula
  desc "A go-defaults plugin for protoc"
  homepage "https://github.com/protoc-extensions/protoc-gen-go-defaults"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/protoc-extensions/protoc-gen-go-defaults/releases/download/v0.0.1/protoc-gen-go-defaults_0.0.1_darwin_arm64.tar.gz"
      sha256 "9884ea8962adc9980dbcd9702170f81e62033edcaeacdf858e374af65230e739"

      def install
        bin.install "protoc-gen-go-defaults"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/protoc-extensions/protoc-gen-go-defaults/releases/download/v0.0.1/protoc-gen-go-defaults_0.0.1_darwin_amd64.tar.gz"
      sha256 "832eff6e91875bca1c2fd1421146708a27cf1c1986c10f8dfdf951b01888f9d5"

      def install
        bin.install "protoc-gen-go-defaults"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/protoc-extensions/protoc-gen-go-defaults/releases/download/v0.0.1/protoc-gen-go-defaults_0.0.1_linux_arm64.tar.gz"
      sha256 "632d973ae9439be16394c327be21777d1ec6d8f566c4df06c51fbbabe4202aea"

      def install
        bin.install "protoc-gen-go-defaults"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/protoc-extensions/protoc-gen-go-defaults/releases/download/v0.0.1/protoc-gen-go-defaults_0.0.1_linux_amd64.tar.gz"
      sha256 "4b314e1bc6669c5e5c618621670d1f26a9a6d2259b794c0bf72acb698bc523c4"

      def install
        bin.install "protoc-gen-go-defaults"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/protoc-extensions/protoc-gen-go-defaults/releases/download/v0.0.1/protoc-gen-go-defaults_0.0.1_linux_armv6.tar.gz"
      sha256 "c825b4aa50f0459ec9640390d28d03f2114418db27b99d99d1f2c4a14eeca3bb"

      def install
        bin.install "protoc-gen-go-defaults"
      end
    end
  end
end
