# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ProtocGenGoJson < Formula
  desc "A go-json plugin for protoc"
  homepage "https://github.com/protoc-extensions/protoc-gen-go-json"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/protoc-extensions/protoc-gen-go-json/releases/download/v0.0.1/protoc-gen-go-json_0.0.1_darwin_arm64.tar.gz"
      sha256 "c74dc43ec55abc7ae66a27b8f50ca6c04867a02a0b01528a84aa331fc12ec77d"

      def install
        bin.install "protoc-gen-go-json"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/protoc-extensions/protoc-gen-go-json/releases/download/v0.0.1/protoc-gen-go-json_0.0.1_darwin_amd64.tar.gz"
      sha256 "f723c9de0140195eda7765a830684f2ffe5fa90f6465341561c22942713f00be"

      def install
        bin.install "protoc-gen-go-json"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/protoc-extensions/protoc-gen-go-json/releases/download/v0.0.1/protoc-gen-go-json_0.0.1_linux_armv6.tar.gz"
      sha256 "5282e481c43c7bc60dcd03e12717f9da66ab031c4bf1681fe78adee75e16ff10"

      def install
        bin.install "protoc-gen-go-json"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/protoc-extensions/protoc-gen-go-json/releases/download/v0.0.1/protoc-gen-go-json_0.0.1_linux_arm64.tar.gz"
      sha256 "d554adc61cbf854154244578eab5976a658178c201d29dfe5b12fb7979e80ed3"

      def install
        bin.install "protoc-gen-go-json"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/protoc-extensions/protoc-gen-go-json/releases/download/v0.0.1/protoc-gen-go-json_0.0.1_linux_amd64.tar.gz"
      sha256 "16d1e7c47916f42745ad2def54e1664bc360f424e6b0b40d3022878787eb6de2"

      def install
        bin.install "protoc-gen-go-json"
      end
    end
  end
end
