# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ProtocGenTsResource < Formula
  desc "A ts-resource plugin for protoc"
  homepage "https://github.com/einride/protoc-gen-typescript-aip"
  version "0.3.3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/einride/protoc-gen-typescript-aip/releases/download/v0.3.3/protoc-gen-typescript-aip_0.3.3_darwin_arm64.tar.gz"
      sha256 "38b7bb84cb46ec77a87337bb7aa34119edd88b78fcdce4f52d7d45c58dedf185"

      def install
        bin.install "protoc-gen-typescript-aip" => "protoc-gen-ts-resource"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/einride/protoc-gen-typescript-aip/releases/download/v0.3.3/protoc-gen-typescript-aip_0.3.3_darwin_amd64.tar.gz"
      sha256 "5ffd5652af4f44b323f5e92fbdbea473851c677300e55f692542e6891dd964d1"

      def install
        bin.install "protoc-gen-typescript-aip" => "protoc-gen-ts-resource"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/einride/protoc-gen-typescript-aip/releases/download/v0.3.3/protoc-gen-typescript-aip_0.3.3_linux_arm64.tar.gz"
      sha256 "02bc827f0d99932d0e2c0245213133e8201e00f3f1db72e48d7989f93d8e80f9"

      def install
        bin.install "protoc-gen-typescript-aip" => "protoc-gen-ts-resource"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/einride/protoc-gen-typescript-aip/releases/download/v0.3.3/protoc-gen-typescript-aip_0.3.3_linux_amd64.tar.gz"
      sha256 "0c88a85ac8a82e7326f71e806247198733fb7648fa2ccee360b1a809dd56a0bd"

      def install
        bin.install "protoc-gen-typescript-aip" => "protoc-gen-ts-resource"
      end
    end
  end
end
