# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ProtocGenGoResource < Formula
  desc "A go-resource plugin for protoc"
  homepage "https://github.com/protoc-extensions/protoc-gen-go-resource"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/protoc-extensions/protoc-gen-go-resource/releases/download/v0.0.1/protoc-gen-go-resource_0.0.1_darwin_arm64.tar.gz"
      sha256 "1b32466891c0640fbd0dfcb41843ad9a56a5f7d69b6d6a82f762a142801b9dd1"

      def install
        bin.install "protoc-gen-go-resource"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/protoc-extensions/protoc-gen-go-resource/releases/download/v0.0.1/protoc-gen-go-resource_0.0.1_darwin_amd64.tar.gz"
      sha256 "7a35121b8107ebfe16fc641ac01ee3dd7ec1311ba75a8bdf39a99acdde138234"

      def install
        bin.install "protoc-gen-go-resource"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/protoc-extensions/protoc-gen-go-resource/releases/download/v0.0.1/protoc-gen-go-resource_0.0.1_linux_armv6.tar.gz"
      sha256 "4ce78026155120ccf6ff7fe59a9276002a2693e62507df2398e1825d787881e0"

      def install
        bin.install "protoc-gen-go-resource"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/protoc-extensions/protoc-gen-go-resource/releases/download/v0.0.1/protoc-gen-go-resource_0.0.1_linux_arm64.tar.gz"
      sha256 "711ffb8dd5522db173874941373adf723e2110bb907b6ef967125dfdb5a41243"

      def install
        bin.install "protoc-gen-go-resource"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/protoc-extensions/protoc-gen-go-resource/releases/download/v0.0.1/protoc-gen-go-resource_0.0.1_linux_amd64.tar.gz"
      sha256 "45d3fd924d9d0b24fa3d38c4621c93a205df68a9e93eb4f74c2bdfcc039f07d8"

      def install
        bin.install "protoc-gen-go-resource"
      end
    end
  end
end
